# This is a basic workflow to help you get started with Actions

name: Irony

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
          # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
          python-version: ['3.7.4']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Build
        env:
            USER: ${{ secrets.USER }}
            PASSWORD: ${{ secrets.PASSWORD }}
            HOST: ${{ secrets.HOST }}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
      - name: Commit and push    # 更新README.md
        run: |
          git config --global user.email "1294080265@qq.com"
          git config --global user.name "Ironnnnnny"
          git log log.txt
          git add log.txt
          git commit -m "Github Action  Updated"
          git push
